apiVersion: v1
kind: Service
metadata:
  name: mongodb-test
  labels:
    app: database
spec:
  type: ClusterIP
  selector:
    app: database
  ports:
    - name: http
      protocol: TCP
      port: 27017
      targetPort: 27017
